### ISSUE TITLE
Where do i find User Registration Form in OpenCATS ??? 

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#337] opened 2017-11-23 09:21 UTC
Hello, Am using OpenCats version 0.9.4. i Want provide a user Registration for candidates and as well as  Recruiter.   In Open Cats in Settings-> there will be a option of Administration. it contains many sub-options -> ill select  User Management. in this user management every thing we do it manually, like Grating permissions for access levels, firstname, lastname, password  etc.  & in the documentation  they have said that  in access level Lists, there is two files Config.php and ACL.php. if am going to modify these two files am getting Notice: Undefined Index: D:\\xampp\\htdocs\\ OpenCATS\\lib\\ACL.php on line 63. & Notice: Undefined Index:D:\\xampp\\htdocs\\OpenCATS\\lib\\ACL.php on line 76. 

**Apache error Log**
[Thu Nov 23 12:19:48.608180 2017] [:error] [pid 3260:tid 1708] [client ::1:6932] PHP Notice:  Undefined index:  in D:\\xampp\\htdocs\\OpenCATS\\lib\\ACL.php on line 63
[Thu Nov 23 12:19:48.609181 2017] [:error] [pid 3260:tid 1708] [client ::1:6932] PHP Notice:  Undefined index:  in D:\\xampp\\htdocs\\OpenCATS\\lib\\ACL.php on line 76.
Please help me its very Urgent. if is there any reference or links please provide me. thanks in advance.

**Comment by skrchnavy** [comment] 2017-11-23 10:02
Are you using officialy released version (downloaded from releases) of HEAD from master? Both are marked as 0.9.4.

Do you have ACL enabled? (in your config.php is `const ACCESS_LEVEL_MAP` enabled?)
Is it possible to attach config.php (credentials or sensiive informations could be cleared)?

**Comment by pradeep51** [comment] 2017-11-23 10:13
Am using officially released version..... now am disable the( const ACCESS_LEVEL_MAP in config.php) if i enabled this const ACCESS_LEVEL_MAP am getting Undefined Index error.

**Comment by pradeep51** [comment] 2017-11-23 10:22
*ACL.php*![screenshot** 89](https://user-images.githubusercontent.com/28918414/33168216-2b860d4e-d066-11e7-990e-a8559ff83e2f.png)
*config.php*![screenshot** 90](https://user-images.githubusercontent.com/28918414/33168233-386bbe8c-d066-11e7-8928-4bdeeff24350.png)

**Comment by skrchnavy** [comment] 2017-11-23 10:34
ACCESS_LEVEL_MAP in ACL.php is only example. You should not enable it at all.
ACCESS_LEVEL_MAP in config.php (root folder of application) is where it shall be configured (in newer version it is planed to be extracted to it's own file).

Do you need ACL feature? It allows you to configure special access level for some functionality based on `user category` that is in ACL treated as user's role.

I am not sure but I suspect your user has a category, that is not in ACCESS_LEVEL_MAP. But behavior is strange and I need to reproduce it.

**Comment by pradeep51** [comment] 2017-11-23 11:35
@skrchnavy  as you said. i disabled  ACL.php . and then after all i added some secure objects for ACCESS_LEVEL_MAP for 'candidate' array();..  but  still its showing  this errors.
**URGENT HELP NEEDED ** thanks in advance

Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 61
Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 74
Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 61
Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 74
Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 61
Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 74
Notice: Undefined index: in D:\xampp\htdocs\OpenCATS\lib\ACL.php on line 61

![screenshot 91](https://user-images.githubusercontent.com/28918414/33170958-40ddd3a2-d070-11e7-88fe-1d8abcd59d8e.png)

**Comment by skrchnavy** [comment] 2017-11-23 14:46
I am checking file https://github.com/opencats/OpenCATS/blob/0.9.4/lib/ACL.php
and line 61: https://github.com/opencats/OpenCATS/blob/0.9.4/lib/ACL.php#L61
```
        if( NULL !== ACCESS_LEVEL_MAP[$userCategory][$securedObjectName])
```
and line 74: https://github.com/opencats/OpenCATS/blob/0.9.4/lib/ACL.php#L74
```
        if( NULL !== ACCESS_LEVEL_MAP[$userCategory][ACL::SECOBJ_ROOT])
```

I think the error is reported due to: `ACCESS_LEVEL_MAP[$userCategory]`, that is, user category of logged user is not defined in your map.
there are 2 user categories (roles) in your map:
* `candidate`
* `demo`

So user shall have a user category (`candidate`?) from this list. Or if user is without category, an empty category shall be defined in access level map:
```
const ACCESS_LEVEL_MAP = array(
        '' => array(
        ),
        'candidate' => array(
        ),
...
```

Anyway, there is an error in checks that have to be fixed in ACL.php code, it shall treat properly empty category even not defined in access level map.

**Comment by pradeep51** [comment] 2017-11-24 05:16
@skrchnavy, 

**How to define user category of logged user in my map**

`_**> As you said i defined **_`

But it is Still not Working.

> So user shall have a user category (candidate?) from this list. Or if user is without category, an empty category shall be defined in access level map:
> 
> const ACCESS_LEVEL_MAP = array(
>         '' => array(
>         ),
>         'candidate' => array(
>         ),
> ...
> 
![screenshot 92](https://user-images.githubusercontent.com/28918414/33196227-7800530c-d104-11e7-980f-bca1acbfc167.png)

**Comment by skrchnavy** [comment] 2017-11-26 11:59
I tested the code and openCATS was working with reporting these errors.
Anyway, I did some changes in code and you can replace in lib/ACL.php function `    public static function getAccessLevel($securedObjectName, $userCategories, $defaultAccessLevel)
` with this implementation.

with this implementation (added one new function also)
```
    /* Returns accessLevel to securedObjectName for user with userCategories 
     * current implementation evaluates only first user category
    */
    public static function getAccessLevel($securedObjectName, $userCategories, $defaultAccessLevel)
    {
        if( !defined('ACCESS_LEVEL_MAP') || empty(ACCESS_LEVEL_MAP))
        {
            return $defaultAccessLevel;
        }

        $userCategory = ACL::CATEGORY_EMPTY;
        if( isset($userCategories) && count($userCategories) > 0 && isset($userCategories[0]) )
        {
            // for now, only first category is used for evalualtion
            $userCategory = $userCategories[0];
        }
        if( ACL::_hasACLEntry($userCategory, $securedObjectName))
        {
            return ACCESS_LEVEL_MAP[$userCategory][$securedObjectName];
        }

        while(($pos = strrpos($securedObjectName, ".")) !== false)
        {
            $securedObjectName = substr($securedObjectName, 0, $pos);
            if( ACL::_hasACLEntry($userCategory, $securedObjectName))
            {
                return ACCESS_LEVEL_MAP[$userCategory][$securedObjectName];
            }
        }
        if( ACL::_hasACLEntry($userCategory, ACL::SECOBJ_ROOT))
        {
            return ACCESS_LEVEL_MAP[$userCategory][ACL::SECOBJ_ROOT];
        }
        return $defaultAccessLevel;
    }

    public static function _hasACLEntry( $userCategory, $securedObjectName)
    { 
        return array_key_exists($userCategory, ACCESS_LEVEL_MAP)
            && array_key_exists($securedObjectName, ACCESS_LEVEL_MAP[$userCategory])
            && NULL !== ACCESS_LEVEL_MAP[$userCategory][$securedObjectName];
    }
```

**Comment by skrchnavy** [comment] 2017-11-26 12:59
in #339 there is this fix implemented in latest code in master. But not sure what is your real issue, because these php errors should not cause fatal error of openCATS.

**Comment by pradeep51** [comment] 2017-11-27 05:41
Thank you so much @skrchnavy . but i want a User Registration Page. Where Do i find that ?

**Comment by skrchnavy** [comment] 2017-11-27 06:38
The fix is such, that it works without error even with empty map. So when 'role' map not defined,, users default access level is provided.
(default access level is returned in all cases when entry not in map, you have to understand map as extension / change of default level for special cases).

I am not sure if self registration of users is supported in standard setup. There is implementation of something similar using LDAP, when user is present in LDAP, user entry in opencats is created based on data in LDAP but not proper access level, that have to be handled manually)

**Comment by pradeep51** [comment] 2017-11-27 07:07
@skrchnavy Please Give me Some Examples For Candidates secure Objects. what and all secure objects i can add and how do i access them.
in above pic access_level_map has  `'candidate' => array(
            'candidates.edit' => ACCESS_LEVEL_READ,
            'candidates.show' => ACCESS_LEVEL_READ,
            'candidates.search' => ACCESS_LEVEL_READ,
            'candidates.viewResume' => ACCESS_LEVEL_READ,
            'calendar.show' => ACCESS_LEVEL_READ,
            'joborders.show' => ACCESS_LEVEL_READ,
        ),
    `
please give me some examples Man.

**Comment by pradeep51** [comment] 2017-11-28 06:09
@skrchnavy  Thank you So much Man. You Helped me a Lot.

**Closed** 2018-01-15 11:28 UTC
