### ISSUE TITLE
When I Am Trying to add candidate with attached resume Am getting this error

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#353] opened 2018-03-01 06:07 UTC
Deprecated: Function split() is deprecated in C:\wamp64\www\CATS\lib\Attachments.php on line 996
eprecated: Non-static method DatabaseSearch::fulltextEncode() should not be called statically, assuming $this from incompatible context in C:\wamp64\www\CATS\lib\Attachments.php on line 87
Warning: Cannot modify header information - headers already sent by (output started at C:\wamp64\www\CATS\lib\Attachments.php:87) in C:\wamp64\www\CATS\modules\candidates\CandidatesUI.php on line 2733
Warning: Cannot modify header information - headers already sent by (output started at C:\wamp64\www\CATS\lib\Attachments.php:87) in C:\wamp64\www\CATS\lib\CATSUtility.php on line 275

`When i want to create an attachment am getting this error`
Deprecated: Non-static method DatabaseSearch::fulltextEncode() should not be called statically, assuming $this from incompatible context in C:\wamp64\www\CATS\lib\Attachments.php on line 87

![image 2](https://user-images.githubusercontent.com/28918414/36885644-40c5d7b6-1e0e-11e8-8c65-f473118da69f.png)

**Comment by strikingwebsolutions** [comment] 2018-03-19 14:31
These are warnings and likely are not the root cause of the issue you're experiencing.

**Comment by pradeep51** [comment] 2018-03-20 06:55
How do i Fix this @strikingwebsolutions

**Comment by RussH** [comment] 2018-03-20 11:55
@pradeep51 can you confirm your PHP version, MySQL version, and opencats version please?

**Comment by pradeep51** [comment] 2018-03-20 12:04
Php 5.6 ,
OpenCats 0.94
MySQL 5.6.12 am using above these versions

**Comment by RussH** [comment] 2018-03-20 12:29
so to describe the issue, ignoring the warnings above..

a) when you create a candidate in the backend it works
b) after you create a candidate AND THEN add an attachment it throws errors and doesn't work?
as 'adding a candidate with an attached resume' doesn't seem to follow the defined workflow. 

What reproducible steps are you taking that cause the error, and can you recreate it on demo.opencats.org?

Thx

**Comment by RussH** [comment] 2018-09-18 10:44
Hi @pradeep51 is this still an issue? If so, can you provide an update / answer to the questions asked?

**Comment by RussH** [comment] 2018-11-14 16:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by RussH** 2018-11-14 16:35 UTC
Labels: more-information-required
