### ISSUE TITLE
Date issue in activities

### ISSUE THREAD

**Issue by Avupatel1998** [opencats/OpenCATS#452] opened 2019-10-03 11:23 UTC
### Expected behavior and actual behavior.
Expected Behavior: Proper Activity Dates should be displayed in Activity page.
Actual Behavior: Activity Date year is showing next year.
![image](https://user-images.githubusercontent.com/55832217/66122468-637af580-e5fd-11e9-8026-2157e779f6d4.png)

### What version of opencats are you running? 
0.9.4
#### Release or downloaded from Git? 
Realease

### What version of PHP and MySQL are you running
PHP: 5.6.40 
MySQL: MySQL 5.6.45 

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
![image](https://user-images.githubusercontent.com/55832217/66122468-637af580-e5fd-11e9-8026-2157e779f6d4.png)

**Comment by RussH** [comment] 2019-10-03 11:57
Duplicate of #318

**Closed by RussH** 2019-10-03 11:57 UTC
