### ISSUE TITLE
Applicant Page unavailable anywhere except localhost on server 2016

### ISSUE THREAD

**Issue by bluemode** [opencats/OpenCATS#304] opened 2017-07-21 05:50 UTC
### System Information
Windows Server Datacenter 2016 *(Opencats Info screen refers to it as server 2012)*
XAMPP v3.2.2
Composer v4.5
OpenCats 0.9.3
Watched video before installing and followed along with wiki as I installed. 
### Expected behavior and actual behavior.
Applicants should be able to go to blah.com/Opencats and apply to whatever is on there.  

The career section does not appear on localhost or externally. 
After reading the fourms, I discovered this works on localhost but no where else. 
```localhost/OpenCats/index.php?m=careers&p=showAll```
Obviously when trying outside I updated localhost as appropriate. 
### Steps to reproduce the problem.
On windows 10/windows server 2016, install OpenCATS
set up OpenCATS
Try to access page. 
### What version of opencats are you running? WAMP or LAMP? 
OpenCats 0.9.3

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
*none*

**Comment by skrchnavy** [comment] 2017-07-21 07:20
Isn't this same issue as in #292 - @luthviar  and #216 - @cptr  ?

We are using IIS, development on a WAMP and XAMPP, but we are not using career portal so this was not tested, rest works.

**Comment by RussH** [comment] 2017-07-21 07:34
So from outside you can reach opencats but not the career portal?

**Comment by karthikjoe** [comment] 2017-07-21 08:01
In windows localhost career page not working but in linux its working great.

**Comment by RussH** [comment] 2017-07-21 08:06
Must admit I've never run this on windows! Thank you for the update.

**Comment by RussH** [comment] 2017-07-21 08:36
@bluemode as per the update from @karthikjoe this seems to be an IIS issue. Can you see any error logs? presumably windows has some restrictions on what directories it'll serve via the IIS webserver?

**Comment by karthikjoe** [comment] 2017-07-21 10:21
Hi @bluemode using Xampp also not working in windows server 2012 r2 data center.
Because i am also using windows server 2012 R2 Data Center

**Comment by RussH** [comment] 2017-08-23 09:56
Closing as seems to be an IIS issue rather than opencats.

**Comment by evank28** [comment] 2018-01-15 19:34
I am experiencing the same issue. @RussH @bluemode . On Xampp Windows. Localhost. No errors logged. Can you help fix this? I can't use the Careers page whatsoever.

**Comment by RussH** [comment] 2018-01-16 10:09
Hmm, I can't test as I don't have a spare windows 10 box. @skrchnavy can you see if the careers portal runs on your windows ten installation?

**Comment by RussH** [comment] 2018-01-16 14:35
This is a duplicate of issue #332 - because the URL /opencats/careers doesn't resolve it isn't accessible from another PC. There's a workaround to 'see' the career portal locally but that doesn't work for remote access.

**Closed by RussH** 2018-01-16 14:35 UTC
Labels: Check if still an issue
