### ISSUE TITLE
Mismatch bei Date format.

### ISSUE THREAD

**Issue by prolyfix** [opencats/OpenCATS#52] opened 2016-02-10 09:24 UTC
Hi,
(my first comment on GitHub). I Installed OpenCATS yestedays using the date format (DD-MM-YY)
when I create activity and want later to modify it, I have a date mismatch:
Instead of giving me the 10. February .2016 it gives me as Oktober, 2 2016

**Comment by RussH** [comment] 2016-02-12 09:57
Hi, I believe some recent PHP changes mean that if your server timezone isn't the same as your target timezone, you'll have issues. I need to check through the code to see why this is happening - however the quick fix it to have your server time set to the same as your required timezone. Clearly if you're installing on shared hosting this will be a problem until resolved.

**Comment by filippo-basso** [comment] 2017-04-14 01:21
Hi,
seems I've the same problem, when editing an activity that is dated 10-4-2017 (date format DD-MM-AAAA) it is presented below as 4 October 2017, and then if not changed manually, after saving the change it will present 4-10-2017 as activity date.

**Temporary workaround:** use the MM-DD-AAAA date format (but it's not too intuitive for several countries...)

Technically, seems not related with the server timezone, seems:
```
# cat /etc/timezone
Etc/UTC
```

**Comment by RussH** [comment] 2018-09-21 12:02
Closing - duplicate of #344 (also a fix is included in that issue)

**Closed by RussH** 2018-09-21 12:02 UTC
Labels: Reported Bug
