### ISSUE TITLE
'Remember Password' issue is still to be resolved

### ISSUE THREAD

**Issue by KamalJoshiDelhi** [opencats/OpenCATS#156] opened 2016-11-07 15:03 UTC
Well I guess this one has not yet been resolved... 
In my last conversation with Alain, he mentioned that code for forgotten password functionality is yet to be written... Any progress on that issue please???

**Comment by mlespiau** [comment] 2016-11-15 15:46
Why is this marked as resolved? Is the recover password functionality working?

**Comment by RussH** [comment] 2016-11-15 16:18
Closed as duplicate of  #50

**Closed by RussH** 2016-11-15 16:18 UTC
