### ISSUE TITLE
When Adding New Job Order -  it saves the  incorrect Contact or No Contact

### ISSUE THREAD

**Issue by evank28** [opencats/OpenCATS#351] opened 2018-02-19 22:05 UTC
### Expected behavior and actual behavior.
When I select contact "x" it should save contact "x" for that job order, and when viewing and editing that job order it should show contact "x" associated with that job order.
Instead, when I select contact "x" it saves as contact "y" or has no contact saved at all. This displays when I view the job order details and click edit. But, once I edit the job order and reselect contact "x" it saves as it should.

### Steps to reproduce the problem.
I tried reproducing this on the demo site and has the same issue. Create a new contact, associate it with a company and a contact. Save it. Then open that job order.

### What version of opencats are you running? WAMP or LAMP? 
I've tested it using v0.9.4 running in 3 different places: locally on XAMPP, on a web server with PHP 5.6 and using the demo site at demo.opencats.org

@opencats @RussH @cptr13

**Comment by RussH** [comment] 2018-02-20 00:14
Duplicate of #280

**Closed** 2018-09-18 10:47 UTC
