### ISSUE TITLE
career portal Showing Blank...

### ISSUE THREAD

**Issue by pradeep51** [opencats/OpenCATS#332] opened 2017-10-25 09:42 UTC
![screenshot 81](https://user-images.githubusercontent.com/28918414/31992091-f3ac6160-b996-11e7-8f96-3a3a9017aeeb.png)

**Comment by RussH** [comment] 2017-10-25 09:48
Hi, we've seen this reported a few times - always on Windows (WAMP). Can you confirm that's the case - can then can you check any logs (apache error log , apache access log)

- Please also check windows firewall is disabled. 
- Also - due to Windows idiosyncrasies can you open http://12.0.0.1 rather than localhost. 
- Please ensure you prefix this with http://

**Comment by pradeep51** [comment] 2017-10-25 11:59
Hello Russ H, I tried what you said but its not Working.

**Comment by RussH** [comment] 2017-10-25 14:02
Hi! Okay - in that case - can you confirm that this is running on Windows & can you check any logs (apache error log , apache access log) for errors - and paste them here.

**Comment by pradeep51** [comment] 2017-10-26 04:52
hey Russ H. Its showing like this in apache Error log --->
[Thu Oct 26 10:13:09.605276 2017] [:error] [pid 7676:tid 1716] [client ::1:3069] PHP Notice:  Use of undefined constant LOGIN_PENDING_APPROVAL - assumed 'LOGIN_PENDING_APPROVAL' in D:\\xampp\\htdocs\\OpenCATS\\lib\\Session.php on line 778, referer: http://localhost/OpenCATS/

**Comment by skrchnavy** [comment] 2017-10-26 11:46
@pradeep51  this is duplicate of #308 where is described how to solve it.

**Comment by pradeep51** [comment] 2017-10-26 12:10
hello @skrchnavy, Thanks for the response. I want to display careers page. what i did in Settings->Administration->Careers Website->Enable Public Career Portal->i checked all the Check Boxes->there is Built in Templates then i selected CATS 2.0 then i make this as a "SET AS ACTIVE". by default it will provide a  link http://localhost/OpenCATS/careers/ near Career Portal URL. if i click on that link career page is blank.  above Previously i Posted Apache(Error log)  and Apache(access log). please try to give me solutions to solve. Thanks in Advance 

http://localhost/retail/careers/
--




http://localhost/retail/careers/
--


http://localhost/retail/careers/
--





http://localhost/retail/careers/
--




http://localhost/retail/careers/
--

**Comment by pradeep51** [comment] 2017-10-26 12:59
![screenshot 83](https://user-images.githubusercontent.com/28918414/32054302-9f969cae-ba7b-11e7-8a36-0ec22e5e304d.png)

**Comment by RussH** [comment] 2017-11-08 11:59
hi @pradeep51 can you confirm you did the following?

> workaround shall be to add row into lib\Users.php: after define('LOGIN_ROOT_ONLY', -5);
> 
> define('LOGIN_PENDING_APPROVAL',            -6);

**Comment by pradeep51** [comment] 2017-11-10 04:27
Hello @RussH. even i added this define('LOGIN_PENDING_APPROVAL', -6); after this  define('LOGIN_ROOT_ONLY', -5); .still its not working man.
you mentioned this link  http://127.0.0.1/careers/ this is also showing OBJECT NOT FOUND.
![screenshot 85](https://user-images.githubusercontent.com/28918414/32642915-85766524-c5fd-11e7-876e-c02f1ea2a9cd.png)

**Comment by RussH** [comment] 2018-01-15 11:31
Hi @pradeep51 is this still an issue? can you confirm current status please?

**Comment by RussH** [comment] 2018-01-16 14:21
Okay, definitely some Windows strangeness. It will work for me, but there are a few steps (some may or may not be required - didn't repeat without some of them to verify)

1 download xampp **5.6.32** https://www.apachefriends.org/xampp-files/5.6.32/xampp-win32-5.6.32-0-VC11-installer.exe
2 install xampp to c:\xampp
3 say yes to the windows firewall pop-up allowing apache access to the internet
4 copied https://github.com/opencats/OpenCATS/releases/download/0.9.4/opencats-0.9.4-full.zip TO C:\xampp\htdocs
5 right-click on the zip file and uncheck the box 'this file came from another computer and might be blocked"
5 extract zipfile to c:\xampp\htdocs\opencats
6. start apache on the xampp control panel
7. start mysql from control panel
8. click yes to the windows firewall pop-up to allow mysql through the firewall
8. visit localhost/phpmyadmin and create opencats databases
remove install_block folder
I then ran opencats installer with mysql root account as the user to save time
9. logged in with admin / admin
10 enabled careers portal in settings
**doesn't work - blank page.** 
11 revisited career portal page and clicked to select the preferred template (CATS 2.0)

12 Visited these URLs which work
**http://localhost/opencats/index.php?m=careers&templateName=CATS+2.0**
**http://localhost/opencats/index.php?m=careers&p=showAll**
**http://localhost/opencats/index.php?m=careers**

so for now despite windows strangeness there is a workaround. I did enable php error logging to be more talkative but didn't succeed before my lunch hour ran out.. so for now this is the workaround!

**Comment by RussH** [comment] 2018-01-16 14:54
I assume this is caused by \lib\CATSUtility.php in the section starting line 222;
**    //FIXME: This causes problems on IIS. ...**

**Comment by RussH** [comment] 2018-01-16 14:57
This is an issue within /lib/CATSUtility.php

**Comment by evank28** [comment] 2018-01-17 01:24
Thanks @RussH . I found that those URLs work too. But, there are significant issues still:
- The "return to Main" button doesn't work. Instead, it takes me to the administrative end of OpenCats, and allows me to skip re-entering a password!
- When I enter the email and zip code of a candidate that is already in the system, their profile does not come up on the next page... Why is this? I notice that the demo version of OpenCats is missing this capability altogether,
- the footer logo doesn't load -> this is a problem with how the src url is in the blank.tpl inside of the careers module. deleting the "./" from that solved this issue.
![image](https://user-images.githubusercontent.com/34668740/35020584-d7263d86-fafa-11e7-8ac7-4fe715d849f6.png)

**Comment by RussH** [comment] 2018-01-23 11:04
Hi. Agreed - historically, the 'careers portal' hasn't seen allot of attention - and I've never used that functionality - I first used the Joomla plugin, now I use the Wordpress plugin.

The 'workaround URL's' are the equivalent internal URL's - so they would not be publicly accessible, they just show you what the public 'would see'. I will do some further investigation on why XAMPP doesn't show the career portal. Very strange!

**Closed** 2018-09-18 09:49 UTC
