### ISSUE TITLE
  LOGIN_PENDING_APPROVAL - URGENT HELP NEEDED

### ISSUE THREAD

**Issue by karthikjoe** [opencats/OpenCATS#308] opened 2017-08-01 04:42 UTC
LOGIN_PENDING_APPROVAL - assumed 'LOGIN_PENDING_APPROVAL' in /storage/ssd4/526/2231526/public_html/lib/Session.php on line 778
when after login successfully i am getting this errors...
My url showing like : /index.php?m=login&a=attemptLogin
![image](https://user-images.githubusercontent.com/29999315/28809576-dbce2d86-76a1-11e7-9899-602eb26b69ed.png)

**Comment by skrchnavy** [comment] 2017-08-01 07:43
Hi.

This is strange behavior because this status shall be only in case of LDAP authentication.
Possible workaround shall be to add row into `lib\Users.php`: after `define('LOGIN_ROOT_ONLY',            -5);`
```
define('LOGIN_PENDING_APPROVAL',            -6);
```
(or you can add this row into config.php temporary until fixed in next version)

Some questions to be able to understand what is the cause of this status:
- Do you have LDAP or LDAP+DB enabled?
- Is the used you logged in already in DB?
- are you using code from release or from a branch in repository?

**Comment by skrchnavy** [comment] 2017-08-01 08:47
fix in master branch commit: c14a13e220e422b228cb7ca792ab168369d850c8

**Comment by skrchnavy** [comment] 2017-08-01 08:49
@karthikjoe please check your settings in php.ini. You have probably too strict checks for warnings (treated as errors).
we are using:
* `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`
* `display_errors = Off`

**Comment by skrchnavy** [comment] 2017-08-01 16:10
please try to add this row:
```
define('LOGIN_PENDING_APPROVAL',            -6);
```
into config.php or replace User.php with latest version https://github.com/opencats/OpenCATS/blob/master/lib/Users.php
where it shall be fixed.

**Comment by karthikjoe** [comment] 2017-08-03 06:12
Hi @skrchnavy Now wokring smoothly thanks @skrchnavy

**Closed** 2017-08-23 09:53 UTC
