### ISSUE TITLE
To unify documentation for installation

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#76] opened 2016-06-29 10:01 UTC
There are 2 pages describing installation steps:
- https://github.com/opencats/OpenCATS/wiki/Install-on-Windows-Tutorial from part: Step 1 System Connectivity
- https://github.com/opencats/OpenCATS/wiki/Install-on-Linux-Tutorial.--Centos7,-Debian8-and-Ubuntu16.06#install-the-opencats-software

I propose to create extra wiki page with common steps, which can be reused in particular installation manuals.

_Motivation: to create docker installation steps without common part._

**Comment by RussH** [comment] 2016-11-30 17:16
Closed as Duplicate of #97

**Closed by RussH** 2016-11-30 17:16 UTC
