### ISSUE TITLE
I think the GUI backup is broken

### ISSUE THREAD

**Issue by cptr13** [opencats/OpenCATS#253] opened 2017-04-30 12:07 UTC
I'm trying to do the documentation for backup/restore and I can't get it to work in 0.9.3.  Not sure if it's a code change or some sort of permissions change.

The GUI backup is in the admin page, site backup.
It backs up the database and the resumes.  When you click it, it performs a full, restorable backupfile (backup.bak) which can be downloaded through a link after.  It also offers the option of breating an attachment-only backup.
This morning, I tested and the full backup in 0.9.3 doesn't work, but the attachment backup does.  I also tested in 0.9.1a and it does work there.

My initial thinking is that maybe some sort of permissions issue that OpenCATS can't do this, but again, it could be the code changes too.

**Comment by mlespiau** [comment] 2017-05-01 19:54
I've created a PR to fix this issue. I believe the problem is with orphaned attachment which exist in the database but not in the file system (at least that seems to be my case).

**Comment by mlespiau** [comment] 2017-05-02 18:24
Merged in 0.9.4

**Closed by mlespiau** 2017-05-02 18:24 UTC
Labels: Reported Bug, waffle: ready to test
